#https://github.com/ssagarwala/API-Gateway-practice/blob/master/gateway-server/src/main/resources/application.yml

server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: http://localhost:8081 # Target service URL
          predicates:
            - Path=/api/products/** # Incoming URL pattern
        - id: order_route
          uri: http://localhost:8082 # Target service URL
          predicates:
            - Path=/api/orders/** # Incoming URL pattern
        - id: user_route
          uri: http://localhost:8083 # Target service URL
          predicates:
            - Path=/api/users/** # Incoming URL pattern
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
  
#spring.application.name=gateway-service

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.default-zone=http://localhost:8761/eureka
#eureka.instance.hostname=localhost

